theme: jekyll-theme-cayman
title: Personal website of Julien Zhou
description: Personal website of Julien Zhou
# logo: [Location of the logo]
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]
